### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by ombre8** [festivalplaner/festivalplaner#13]
Add oAuth

**Comment by ombre8** [comment]
`GET /users?limit=10&offset=0&sort=-_id 500 161.748 ms - -
OPTIONS /auth/github 204 0.837 ms - -
(node:4855) DeprecationWarning: Mongoose: mpromise (mongoose's default promise library) is deprecated, plug in your own promise library instead: http://mongoosejs.com/docs/promises.html
POST /auth/github 200 1347.779 ms - 112
Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:359:11)
    at ServerResponse.header (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/response.js:719:10)
    at ServerResponse.send (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/response.js:164:12)
    at done (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/response.js:956:10)
    at Object.exports.renderFile (/home/ombre/git/festivalplaner/backend/node_modules/jade/lib/index.js:374:12)
    at View.exports.__express [as engine] (/home/ombre/git/festivalplaner/backend/node_modules/jade/lib/index.js:417:11)
    at View.render (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/view.js:126:8)
    at tryRender (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/application.js:639:10)
    at Function.render (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/response.js:960:7)
    at /home/ombre/git/festivalplaner/backend/config/express.js:61:11
    at Layer.handle_error (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/router/index.js:310:13)
    at /home/ombre/git/festivalplaner/backend/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/router/index.js:330:12)
    at IncomingMessage.next (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/router/index.js:271:10)
    at done (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/response.js:955:25)
    at tryRender (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/application.js:641:5)
    at Function.render (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/application.js:591:3)
    at ServerResponse.render (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/response.js:960:7)
    at /home/ombre/git/festivalplaner/backend/config/express.js:51:11
    at Layer.handle_error (/home/ombre/git/festivalplaner/backend/node_modules/express/lib/router/layer.js:71:5)
OPTIONS /users?limit=10&offset=0&sort=-id 204 0.509 ms - -
GET /users?limit=10&offset=0&sort=-id 404 14.421 ms - -
OPTIONS /artists?limit=30&offset=0&sort=-id 204 0.363 ms - -
GET /artists?limit=30&offset=0&sort=-id 404 7.887 ms - -
GET /users?limit=10&offset=0&sort=-id 500 22.406 ms - -
`
Login kinda works... but no user is created

500er if logged out 👍 
404er if logged in?

Still working on it in #23
